localization es
SnejUgal/attheme-editor pull request #7
Opened 2018-08-10 16:36 UTC by DestroyerIV

2018-08-10 16:41 UTC, SnejUgal commented on src/localizations/es.js
> +    {} con {}
Add yourself here, something like `Created by ... and translated by <Link href="//t.me/NeganLucille">@NeganLucille</Link> with <LoveEmoji/>`

2018-08-10 16:44 UTC, SnejUgal commented on src/localizations/es.js
> +    .attheme editor le permite ejecutar facilemente scripts escritos en EcmaScript 2017 para acelerar el desarrollo de temas. Puede leer mas sobre la API que proporciona el editor <Link href="//githu
Remove the space at the end

2018-08-10 16:50 UTC, SnejUgal commented on src/localizations/es.js
> +      "other other": `${theme} of ${total} las variables se agregan al tema`,
I'm not a Spanish speaker, but I think these should be reviewed (I guess `se agrega` is lined to `1 of ... variable`. Here are some examples of forms when applied:
`1 of 1 variable is added to the theme`
`1 of 2 variables is added to the theme`
`2 of 1 variables are added to the theme`
`2 of 2 variables are added to the theme`

2018-08-10 16:51 UTC, snejugal requested changes
see comments

2019-03-23 14:47 UTC, SnejUgal commented
Whops, forgot to close this PR once I merged #26

2019-03-23 14:47 UTC, closed without merging